### ISSUE TITLE
Check for other players

### ISSUE THREAD

**Issue by abhinayy0** [red-elka/stream-cli#2]
- [ ] Check for multiple players in system if exists play from them or ask to play from them

**Comment by abhinayy0** [comment]
@red-elka  I am not able to pickup the playable url if we can get that from magnet link than all we need to check for vlc, if it exists 
we can just open the subprocess to run it. Is their any way to get the playable url from magnet link.

**Comment by red-elka** [comment]
yes there's is but currently i only added mpv media player, i'm gonna add vlc

**Comment by red-elka** [comment]
i added the ability to choose your favorite  media player.
can you test it?

**Comment by abhinayy0** [comment]
It's working but i think the code is supported in Linux only. If so you should mention that.
